// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_riGIlfPxuO6xgWgh0fHP730577RIKrg',
    appId: '1:900996414993:web:5384e38368f7355528fbb0',
    messagingSenderId: '900996414993',
    projectId: 'lendydemonew',
    authDomain: 'lendydemonew.firebaseapp.com',
    storageBucket: 'lendydemonew.appspot.com',
    measurementId: 'G-R9F3LGY0VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVdXsK8s4sw5PQGHB76zy9WDAVgGwH-4',
    appId: '1:900996414993:android:7476b172456d1dee28fbb0',
    messagingSenderId: '900996414993',
    projectId: 'lendydemonew',
    storageBucket: 'lendydemonew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJuph3HsJmQYhwwt6jGKAN1ZsDStfgVP4',
    appId: '1:900996414993:ios:fb7f9822d205fb4e28fbb0',
    messagingSenderId: '900996414993',
    projectId: 'lendydemonew',
    storageBucket: 'lendydemonew.appspot.com',
    iosBundleId: 'com.example.androidflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJuph3HsJmQYhwwt6jGKAN1ZsDStfgVP4',
    appId: '1:900996414993:ios:66bbd3d44654359128fbb0',
    messagingSenderId: '900996414993',
    projectId: 'lendydemonew',
    storageBucket: 'lendydemonew.appspot.com',
    iosBundleId: 'com.example.androidflutter.RunnerTests',
  );
}
