name: androidflutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mapbox_maps_flutter: ^0.5.1
    #git:
     # url: https://github.com/mapbox/mapbox-maps-flutter.git
     # ref: main # or the specific branch, tag, or commit you want to use
    #path: "C:/Users/water/Downloads/mapbox_maps_flutter-0.5.1"
    
  permission_handler: ^11.1.0 # Added location etc
  http: ^1.1.2
  turf: ^0.0.8
  go_router: ^13.1.0 # For in Application Navigation
  table_calendar: ^3.0.3 # calendar stuff
  intl: ^0.18.1 # calendar stuff
  timezone: ^0.9.2 # calendar stuff
  syncfusion_flutter_gauges: ^24.1.47 # radial progress bar
  syncfusion_flutter_calendar: ^24.1.47
  custom_date_range_picker: ^1.0.1
  syncfusion_flutter_datepicker: ^24.1.47
  shared_preferences: ^2.0.6
  firebase_core: ^2.25.2
  firebase_storage: ^11.6.6
  #firebase_auth: ^3.3.3
  #firebase_messaging: ^14.7.13
  #firebase_database: ^10.1.3
  #firebase_storage: ^11.6.3
  cloud_firestore: ^4.15.2
  #solana_mobile_stack: ^latest_version
  encrypt: ^5.0.3
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  pointycastle: ^3.7.4
  langchain: ^0.4.1
  langchain_chroma: ^0.1.1
  langchain_pinecone: ^0.0.7
  langchain_openai: ^0.4.1

  font_awesome_flutter: ^10.7.0

  flutter_launcher_icons: "^0.9.2"

  geojson: ^1.0.0

  image_picker: ^1.0.7

  flutter_hooks: ^0.20.5

  carousel_slider: ^4.2.1 

  #mapbox_gl: ^0.16.0



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data.geojson
    - assets/
    - assets/images/
    - assets/
    - assets/symbols/
    - assets/cluster/
    - assets/assets/
    - assets/earthquakes.geojson

flutter_icons:
  android: true 
  ios: true
  image_path: "icons/icon.png" # Replace with your icon's path